version: '3'

services:
    # app:
    #     container_name: abcTeamContainer
    #     image: nhlcoding
    #     build: .
    #     ports:
    #         - '3000:3000'
    #     depends_on:
    #         - db

    db:
        container_name: abcTeamDB
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=abcTeam
            - POSTGRES_DB=abcDatabase
